// <auto-generated />
using System;
using Hamburgercim.Models.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hamburgercim.Data.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hamburgercim.Models.Data.Classes.Boyut", b =>
                {
                    b.Property<int>("BoyutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoyutId"), 1L, 1);

                    b.Property<string>("BoyutAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BoyutFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BoyutId");

                    b.ToTable("Boyutlar");
                });

            modelBuilder.Entity("Hamburgercim.Models.Data.Classes.EkstraMalzeme", b =>
                {
                    b.Property<int>("EkstraMalzemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EkstraMalzemeId"), 1L, 1);

                    b.Property<string>("EkstraMalzemeAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EkstraMalzemeFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SiparisId")
                        .HasColumnType("int");

                    b.HasKey("EkstraMalzemeId");

                    b.HasIndex("SiparisId");

                    b.ToTable("EkstraMalzemeler");
                });

            modelBuilder.Entity("Hamburgercim.Models.Data.Classes.Hamburger", b =>
                {
                    b.Property<int>("HamburgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HamburgerId"), 1L, 1);

                    b.Property<string>("HamburgerAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HamburgerFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HamburgerFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HamburgerId");

                    b.ToTable("Hamburgerler");
                });

            modelBuilder.Entity("Hamburgercim.Models.Data.Classes.Icecek", b =>
                {
                    b.Property<int>("IcecekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcecekId"), 1L, 1);

                    b.Property<string>("IcecekAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IcecekFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IcecekId");

                    b.ToTable("Icecekler");
                });

            modelBuilder.Entity("Hamburgercim.Models.Data.Classes.Siparis", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"), 1L, 1);

                    b.Property<int>("BoyutId")
                        .HasColumnType("int");

                    b.Property<int>("HamburgerId")
                        .HasColumnType("int");

                    b.Property<int?>("IcecekId")
                        .HasColumnType("int");

                    b.Property<byte>("SiparisAdet")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SiparisId");

                    b.HasIndex("BoyutId");

                    b.HasIndex("HamburgerId");

                    b.HasIndex("IcecekId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("Hamburgercim.Models.Data.Classes.EkstraMalzeme", b =>
                {
                    b.HasOne("Hamburgercim.Models.Data.Classes.Siparis", "Siparis")
                        .WithMany("EkstraMalzeme")
                        .HasForeignKey("SiparisId");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Hamburgercim.Models.Data.Classes.Siparis", b =>
                {
                    b.HasOne("Hamburgercim.Models.Data.Classes.Boyut", "Boyut")
                        .WithMany()
                        .HasForeignKey("BoyutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburgercim.Models.Data.Classes.Hamburger", "Hamburger")
                        .WithMany()
                        .HasForeignKey("HamburgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hamburgercim.Models.Data.Classes.Icecek", "Icecek")
                        .WithMany()
                        .HasForeignKey("IcecekId");

                    b.Navigation("Boyut");

                    b.Navigation("Hamburger");

                    b.Navigation("Icecek");
                });

            modelBuilder.Entity("Hamburgercim.Models.Data.Classes.Siparis", b =>
                {
                    b.Navigation("EkstraMalzeme");
                });
#pragma warning restore 612, 618
        }
    }
}
